# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib

PATH_ROOT = pathlib.Path()
PATH_JSON = PATH_ROOT.absolute() / 'DB' / 'cadastro.json'

class signin_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(527, 640)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 481, 50))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nome_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nome_label.setObjectName("nome_label")
        self.verticalLayout.addWidget(self.nome_label)
        self.input_nome = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.input_nome.setObjectName("input_nome")
        self.verticalLayout.addWidget(self.input_nome)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 130, 481, 50))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sobrenome_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.sobrenome_label.setObjectName("sobrenome_label")
        self.verticalLayout_2.addWidget(self.sobrenome_label)
        self.input_sobrenome = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.input_sobrenome.setObjectName("input_sobrenome")
        self.verticalLayout_2.addWidget(self.input_sobrenome)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 220, 481, 50))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sobrenome_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.sobrenome_label_2.setObjectName("sobrenome_label_2")
        self.verticalLayout_3.addWidget(self.sobrenome_label_2)
        self.input_sobrenome_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.input_sobrenome_2.setObjectName("input_sobrenome_2")
        self.verticalLayout_3.addWidget(self.input_sobrenome_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 300, 481, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sobrenome_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.sobrenome_label_3.setObjectName("sobrenome_label_3")
        self.verticalLayout_4.addWidget(self.sobrenome_label_3)
        self.input_sobrenome_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.input_sobrenome_3.setObjectName("input_sobrenome_3")
        self.verticalLayout_4.addWidget(self.input_sobrenome_3)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 380, 481, 50))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.nome_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.nome_label_3.setObjectName("nome_label_3")
        self.verticalLayout_5.addWidget(self.nome_label_3)
        self.input_nome_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_nome_3.setObjectName("input_nome_3")
        self.verticalLayout_5.addWidget(self.input_nome_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 450, 481, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setFixedSize(525, 600)
        self.nome_label.setText(_translate("Form", "Nome:"))
        self.sobrenome_label.setText(_translate("Form", "Sobrenome:"))
        self.sobrenome_label_2.setText(_translate("Form", "Email:"))
        self.sobrenome_label_3.setText(_translate("Form", "Email repetido:"))
        self.nome_label_3.setText(_translate("Form", "Número de telefone:"))
        self.pushButton.setText(_translate("Form", "Pronto!"))
        self.pushButton.clicked.connect(self.novo_usuario)
    def novo_usuario(self):
        flag = True
        import json
        cont = 0
        nova_pessoa = {}
        nova_pessoa.setdefault('_id_', str(cont))
        nova_pessoa.setdefault('Nome', self.input_nome.text())
        nova_pessoa.setdefault('Sobrenome', self.input_sobrenome.text())
        nova_pessoa.setdefault('Telefone', self.input_nome_3.text())
        if self.input_sobrenome_2.text() == self.input_sobrenome_3.text():
            nova_pessoa.setdefault('Email', self.input_sobrenome_2.text())
        else:
            print('erro, digite o email igual')
            from error import error_ui
            self.MainWindowError = QtWidgets.QMainWindow()
            self.ui_error = error_ui()
            self.ui_error.setupUi(self.MainWindowError)
            self.MainWindowError.show()

            flag = False

        print('cadastrado')
        if flag is True:
            with open(PATH_JSON, 'a+', encoding='utf-8') as file:
                json.dump(nova_pessoa, file, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = signin_ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
